name:        Guerilla Labs
dev:         false

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     [ sass, Rakefile, codekit-config.json, README.md ]

future:      true
show_drafts: nil
pygments:    false

relative_permalinks: false

permalink:   /:categories/:title.html

paginate:    25
paginate_path: "blog/page:num"
