name:        Guerilla Labs
description: The experiments, musings, case-studies, and frivolity of Guerilla Labs.
dev:         false

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://guerillalabs.co
lsi:         false
markdown:    kramdown

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     [ sass, Rakefile, codekit-config.json, README.md ]

future:      true
show_drafts: nil

relative_permalinks: false

permalink:   /:categories/:title.html

paginate:    25
paginate_path: "blog/page:num"
